#!/bin/sh
# Copyright (C) 2019, Digi International

part_name="rootB"
ubidev_path="/dev/ubi2"

source /init.d/init-common.sh

initrootB_enabled() {
	resin_check_ubivol $part_name && return 1
	return 0
}

initrootB_run() {
	resin_mkubivol $part_name $ubidev_path
}
