#!/bin/sh
# Copyright (C) 2019, Digi International

part_name="state"
ubidev_path="/dev/ubi0"

source /init.d/init-common.sh

initstate_enabled() {
	resin_check_ubivol $part_name && return 1
	return 0
}

initstate_run() {
	resin_mkubivol $part_name $ubidev_path
}
