#!/bin/sh

#
# Script used by hostapps updater to flash bootloader onto internal media
#

set -o errexit

# machine specific data
uboot_file="imx-boot"
uboot_block_size=1024
uboot_seek_blocks=33
device="/dev/mmcblk2boot0"

update_files="uboot"

for i in $update_files; do
	current_update_file=$(eval echo \$${i}_file)
	block_size=$(eval echo \$${i}_block_size)
	seek_blocks=$(eval echo \$${i}_seek_blocks)

	# calculate size and md5sum of the binary to update from the update bundle
	update_size=$(ls -al /resin-boot/$current_update_file | awk '{print $5}')
	update_md5sum=$(md5sum /resin-boot/$current_update_file | awk '{print $1'})

	let skip_bytes=$block_size*$seek_blocks

	# calculate md5sum of the data already written to $device, using $update_size bytes and skipping $skip_bytes from $device
	existing_md5sum=$(dd if=$device bs=1 skip=$skip_bytes count=$update_size status=none | md5sum | awk '{print $1}')

	# This hw partition should NOT be erased on imx8mm-lpddr4-evk, as it might contain an u-boot eMMC environment
	if [ ! "$existing_md5sum" = "$update_md5sum" ]; then
		echo "Will update u-boot on /dev/mmcblk2boot0"
		echo 0 > /sys/block/mmcblk2boot0/force_ro
		dd if=/resin-boot/$current_update_file of=$device conv=fdatasync seek=$seek_blocks bs=$block_size
		echo 1 > /sys/block/mmcblk2boot0/force_ro
	fi
done
